import { Tour, Testimonial } from '@/types';

export const mockTours: Tour[] = [
  {
    id: '1',
    title: 'Cultural Triangle Explorer',
    description: 'Discover the ancient kingdoms of Sri Lanka with visits to UNESCO World Heritage sites including Sigiriya, Dambulla, and Polonnaruwa. Experience the rich cultural heritage and stunning architecture.',
    shortDescription: 'Explore ancient kingdoms and UNESCO sites in 5 days',
    price: 599,
    duration: '5 Days / 4 Nights',
    image: 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800&q=80',
      'https://images.unsplash.com/photo-1568102444039-65d2e0102c6b?w=800&q=80',
    ],
    region: 'Cultural Triangle',
    highlights: [
      'Climb Sigiriya Rock Fortress',
      'Explore Dambulla Cave Temple',
      'Visit ancient Polonnaruwa ruins',
      'Traditional Sri Lankan cuisine',
    ],
    rating: 4.9,
    reviewCount: 127,
    itinerary: [
      {
        day: 1,
        title: 'Arrival & Sigiriya',
        description: 'Arrive in Colombo and transfer to Sigiriya. Evening visit to the iconic Sigiriya Rock Fortress.',
        activities: ['Airport pickup', 'Sigiriya Rock climb', 'Sunset views'],
      },
      {
        day: 2,
        title: 'Dambulla & Minneriya',
        description: 'Morning visit to Dambulla Cave Temple, afternoon safari at Minneriya National Park.',
        activities: ['Cave temple tour', 'Elephant safari', 'Wildlife photography'],
      },
      {
        day: 3,
        title: 'Polonnaruwa Ancient City',
        description: 'Full day exploring the ancient ruins of Polonnaruwa, a UNESCO World Heritage Site.',
        activities: ['Ancient ruins tour', 'Cycling around the city', 'Local lunch'],
      },
      {
        day: 4,
        title: 'Anuradhapura',
        description: 'Visit the sacred city of Anuradhapura with its ancient stupas and sacred Bodhi tree.',
        activities: ['Sacred sites tour', 'Cultural immersion', 'Temple visits'],
      },
      {
        day: 5,
        title: 'Departure',
        description: 'Morning at leisure, transfer to Colombo airport for departure.',
        activities: ['Shopping', 'Airport transfer'],
      },
    ],
    included: [
      'Airport transfers',
      'Accommodation (4-star hotels)',
      'Daily breakfast',
      'All entrance fees',
      'English-speaking guide',
      'Air-conditioned vehicle',
    ],
    excluded: [
      'International flights',
      'Lunch and dinner',
      'Personal expenses',
      'Travel insurance',
      'Tips and gratuities',
    ],
  },
  {
    id: '2',
    title: 'Beach & Wildlife Adventure',
    description: 'Combine pristine beaches with thrilling wildlife safaris. Experience leopards in Yala, whales in Mirissa, and relax on golden beaches.',
    shortDescription: 'Beach relaxation meets wildlife adventure in 7 days',
    price: 799,
    duration: '7 Days / 6 Nights',
    image: 'https://images.unsplash.com/photo-1566552881560-0be862a7c445?w=800&q=80',
    region: 'South Coast',
    highlights: [
      'Yala National Park safari',
      'Whale watching in Mirissa',
      'Beach time in Unawatuna',
      'Galle Fort exploration',
    ],
    rating: 4.8,
    reviewCount: 89,
  },
  {
    id: '3',
    title: 'Hill Country Tea Trail',
    description: 'Journey through the misty hills of Sri Lanka, visiting tea plantations, waterfalls, and colonial towns like Nuwara Eliya and Ella.',
    shortDescription: 'Scenic train rides and tea estates for 6 days',
    price: 699,
    duration: '6 Days / 5 Nights',
    image: 'https://images.unsplash.com/photo-1583309636511-f8db749e63e7?w=800&q=80',
    region: 'Hill Country',
    highlights: [
      'Scenic train journey to Ella',
      'Tea plantation tours',
      'Nine Arch Bridge visit',
      'Horton Plains trek',
    ],
    rating: 4.9,
    reviewCount: 156,
  },
  {
    id: '4',
    title: 'Complete Island Circuit',
    description: 'The ultimate Sri Lankan adventure covering culture, wildlife, beaches, and hill country. A comprehensive 12-day journey.',
    shortDescription: 'Experience all of Sri Lanka in 12 unforgettable days',
    price: 1499,
    duration: '12 Days / 11 Nights',
    image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80',
    region: 'Island-wide',
    highlights: [
      'All major UNESCO sites',
      'Multiple safari experiences',
      'Beach relaxation',
      'Hill country exploration',
    ],
    rating: 5.0,
    reviewCount: 203,
  },
  {
    id: '5',
    title: 'Adventure & Adrenaline',
    description: 'For thrill-seekers! White water rafting, hiking, zip-lining, and surfing across Sri Lanka\'s most adventurous destinations.',
    shortDescription: 'Action-packed 8 days of extreme adventures',
    price: 899,
    duration: '8 Days / 7 Nights',
    image: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&q=80',
    region: 'Multi-region',
    highlights: [
      'White water rafting',
      'Ella Rock hiking',
      'Surfing in Arugam Bay',
      'Zip-lining adventures',
    ],
    rating: 4.7,
    reviewCount: 94,
  },
  {
    id: '6',
    title: 'Spiritual & Wellness Retreat',
    description: 'Find inner peace with yoga, meditation, Ayurveda treatments, and visits to sacred Buddhist sites.',
    shortDescription: 'Rejuvenate mind and body in 10 peaceful days',
    price: 1199,
    duration: '10 Days / 9 Nights',
    image: 'https://images.unsplash.com/photo-1545389336-cf090694435e?w=800&q=80',
    region: 'Central & South',
    highlights: [
      'Daily yoga and meditation',
      'Ayurveda spa treatments',
      'Temple visits',
      'Organic cuisine',
    ],
    rating: 4.9,
    reviewCount: 67,
  },
];

export const mockTestimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    country: 'United Kingdom',
    rating: 5,
    comment: 'Triple SR Travelers made our honeymoon absolutely magical! The Cultural Triangle tour was perfectly organized, and our guide was incredibly knowledgeable. Every detail was taken care of.',
    image: 'https://i.pravatar.cc/150?img=1',
    date: '2024-10-15',
  },
  {
    id: '2',
    name: 'Michael Chen',
    country: 'Australia',
    rating: 5,
    comment: 'Best adventure trip ever! The wildlife safaris were breathtaking and we saw leopards, elephants, and so much more. Highly recommend for anyone visiting Sri Lanka.',
    image: 'https://i.pravatar.cc/150?img=13',
    date: '2024-09-28',
  },
  {
    id: '3',
    name: 'Emma Schmidt',
    country: 'Germany',
    rating: 5,
    comment: 'The tea country tour exceeded all expectations. Beautiful landscapes, wonderful people, and the train journey was unforgettable. Thank you Triple SR Travelers!',
    image: 'https://i.pravatar.cc/150?img=5',
    date: '2024-11-02',
  },
  {
    id: '4',
    name: 'David Martinez',
    country: 'USA',
    rating: 5,
    comment: 'Exceptional service from start to finish. The team was responsive, professional, and went above and beyond to ensure we had an amazing experience. Will definitely book again!',
    image: 'https://i.pravatar.cc/150?img=12',
    date: '2024-10-20',
  },
];
